PROJECT:={{.ProjectName}}
CONFIG_FILE:=settings.yaml
GO_MODULE_STATE:=$(shell go env GO111MODULE)
GO_PROXY:=$(shell go env GOPROXY)


.PHONY: build dep serve clean

.DEFAULT: build

build: 
	CGO_ENABLE=0 go build -o ${PROJECT} main.go

dep:
ifneq ($(GO_MODULE_STATE), on)
	go env -w GO111MODULE="on"
endif
ifeq ($(GO_PROXY), https://proxy.golang.org,direct)
	go env -w GOPROXY="https://goproxy.cn,direct"
endif
	go mod tidy


serve: build
		./${PROJECT} serve -c ./config/${CONFIG_FILE} 

clean:
	rm -rf ${PROJECT}
